-- Create Documents table for LaTeXify AI history

CREATE TABLE IF NOT EXISTS public."Documents" (
    id bigint generated by default as identity primary key,
    title text,
    input_text text,
    instructions text,
    latex_code text,
    status text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Alternatively, lowercase variant if preferred:
-- CREATE TABLE IF NOT EXISTS public.documents (
--     id bigint generated by default as identity primary key,
--     title text,
--     input_text text,
--     instructions text,
--     latex_code text,
--     status text,
--     created_at timestamp with time zone default timezone('utc'::text, now()) not null
-- );