-- Create Documents table for LaTeXify AI history

CREATE TABLE IF NOT EXISTS public."Documents" (
    id bigint generated by default as identity primary key,
    title text,
    user_email text,
    input_text text,
    instructions text,
    latex_code text,
    pdf_base64 text,
    status text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public."Documents"
ADD COLUMN IF NOT EXISTS user_email text;

CREATE INDEX IF NOT EXISTS documents_user_email_idx ON public."Documents"(user_email);

CREATE TABLE IF NOT EXISTS public.otp_codes (
    email text primary key,
    otp_code text not null,
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Alternatively, lowercase variant if preferred:
-- CREATE TABLE IF NOT EXISTS public.documents (
--     id bigint generated by default as identity primary key,
--     title text,
--     input_text text,
--     instructions text,
--     latex_code text,
--     pdf_base64 text,
--     status text,
--     created_at timestamp with time zone default timezone('utc'::text, now()) not null
-- );
