-- Create Documents table for LaTeXify AI history

CREATE TABLE IF NOT EXISTS public."Documents" (
    id bigint generated by default as identity primary key,
    title text,
    user_email text,
    input_text text,
    instructions text,
    latex_code text,
    pdf_base64 text,
    status text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public."Documents"
ADD COLUMN IF NOT EXISTS user_email text;

CREATE INDEX IF NOT EXISTS documents_user_email_idx ON public."Documents"(user_email);

CREATE TABLE IF NOT EXISTS public.otp_codes (
    email text primary key,
    otp_code text not null,
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Security hardening for Supabase advisor warnings
-- 1) Ensure RLS is enabled
ALTER TABLE IF EXISTS public."Documents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.otp_codes ENABLE ROW LEVEL SECURITY;

-- 2) Remove broad table privileges so objects are not exposed via GraphQL to anon/authenticated users
REVOKE ALL ON TABLE public."Documents" FROM anon, authenticated;
REVOKE ALL ON TABLE public.documents FROM anon, authenticated;
REVOKE ALL ON TABLE public.otp_codes FROM anon, authenticated;

-- 3) Lock down SECURITY DEFINER helper function from public/authenticated execution
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM authenticated;

-- 4) RLS policies: allow only service_role (used by backend) to read/write
DROP POLICY IF EXISTS documents_service_role_all ON public."Documents";
CREATE POLICY documents_service_role_all
ON public."Documents"
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS documents_lc_service_role_all ON public.documents;
CREATE POLICY documents_lc_service_role_all
ON public.documents
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS otp_codes_service_role_all ON public.otp_codes;
CREATE POLICY otp_codes_service_role_all
ON public.otp_codes
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Alternatively, lowercase variant if preferred:
-- CREATE TABLE IF NOT EXISTS public.documents (
--     id bigint generated by default as identity primary key,
--     title text,
--     input_text text,
--     instructions text,
--     latex_code text,
--     pdf_base64 text,
--     status text,
--     created_at timestamp with time zone default timezone('utc'::text, now()) not null
-- );
